<?php

use xoritTheme\Constants\Constants;

use function xoritTheme\ACF\FieldSets\get_three_cards_fields;

$suffix = md5( Constants::ACF_FIELD_CONTACTS );

acf_add_local_field_group(
	array(
		'key'                   => 'group_6963cab3aa325' . $suffix,
		'title'                 => esc_attr__( 'Контакты', 'xorit' ),
		'fields'                => array(
			array(
				'key'               => 'field_6963ccedd92ac' . $suffix,
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_6963cab4d92a5' . $suffix,
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => esc_attr__( 'Используется заголовок поста, если пусто', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_6963cbadd92a6' . $suffix,
				'label'             => esc_attr__( 'Описание', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_description',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 4,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_6963cbd8d92a7' . $suffix,
				'label'             => esc_attr__( 'Телефон', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_phone',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => esc_attr__( 'Если не заполнено, используются настройки сайта', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_6963cc0fd92a8' . $suffix,
				'label'             => esc_attr__( 'Email', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_email',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => esc_attr__( 'Если не заполнено, используются настройки сайта', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_6963cc40d92a9' . $suffix,
				'label'             => esc_attr__( 'Адрес', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_address',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => esc_attr__( 'Если не заполнено, используются настройки сайта', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_6963cc67d92aa' . $suffix,
				'label'             => esc_attr__( 'Кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_cta',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),
			array(
				'key'               => 'field_6963cc9ed92ab' . $suffix,
				'label'             => esc_attr__( 'Код карты', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_map',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => '',
				'placeholder'       => '',
				'new_lines'         => '',
			),
			array(
				'key'               => 'field_6963cd16d92ad' . $suffix,
				'label'             => esc_attr__( 'Документы', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_6963cd3dd92ae' . $suffix,
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_documents_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_6963cab4d9ng5' . $suffix,
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_documents_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_6963cd79d92af' . $suffix,
				'label'             => esc_attr__( 'Документы', 'xorit' ),
				'name'              => Constants::ACF_FIELD_CONTACTS . '_documents_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_6963cda1d92b0' . $suffix,
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_6963cd79d92af' . $suffix,
					),
					array(
						'key'               => 'field_6963cdd6d92b1' . $suffix,
						'label'             => esc_attr__( 'Файл', 'xorit' ),
						'name'              => 'file',
						'aria-label'        => '',
						'type'              => 'file',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
						'library'           => 'all',
						'min_size'          => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'parent_repeater'   => 'field_6963cd79d92af' . $suffix,
					),
				),
			),

			// Three cards
			...get_three_cards_fields( Constants::ACF_FIELD_CONTACTS ),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page_template',
					'operator' => '==',
					'value'    => 'templates/contacts.php',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
		'display_title'         => '',
	)
);
