<?php

use xoritTheme\Constants\Constants;

acf_add_local_field_group(
	array(
		'key'                   => 'group_68fb8fdf64607',
		'title'                 => esc_attr__( 'Главная', 'xorit' ),
		'fields'                => array(
			array(
				'key'               => 'field_68fb8fe060651',
				'label'             => esc_attr__( 'Главный баннер', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fb907f60652',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_hero_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => 150,
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fb90c760653',
				'label'             => esc_attr__( 'Описание', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_hero_description',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => 300,
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fb911760654',
				'label'             => esc_attr__( 'Кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_hero_cta',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),
			array(
				'key'               => 'field_68fb916760655',
				'label'             => esc_attr__( 'Преимущества', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_hero_advantages',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 6,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_68fb91a460656',
						'label'             => esc_attr__( 'Преимущество', 'xorit' ),
						'name'              => 'advantage',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 300,
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_68fb916760655',
					),
				),
			),
			array(
				'key'               => 'field_68fc79541c656',
				'label'             => esc_attr__( 'Задачи', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681c657',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91c658',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc813e1c659',
				'label'             => esc_attr__( 'Задачи', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_68fc817c1c65a',
						'label'             => esc_attr__( 'Иконка', 'xorit' ),
						'name'              => 'icon',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '10',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
						'parent_repeater'   => 'field_68fc813e1c659',
					),
					array(
						'key'               => 'field_68fc81f31c65b',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_68fc813e1c659',
					),
					array(
						'key'               => 'field_68fc82351c65c',
						'label'             => esc_attr__( 'Описание', 'xorit' ),
						'name'              => 'description',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 4,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_68fc813e1c659',
					),
				),
			),
			array(
				'key'               => 'field_68fc827d1c65d',
				'label'             => esc_attr__( 'Красная кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_cta_red',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),
			array(
				'key'               => 'field_68fc82a91c65e',
				'label'             => esc_attr__( 'Белая кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_cta_white',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page_type',
					'operator' => '==',
					'value'    => 'front_page',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
		'display_title'         => '',
	)
);
