<?php

use xoritTheme\Constants\Constants;

acf_add_local_field_group(
	array(
		'key'                   => 'group_68fb8fdf64607',
		'title'                 => esc_attr__( 'Главная', 'xorit' ),
		'fields'                => array(
			array(
				'key'               => 'field_68fb8fe060651',
				'label'             => esc_attr__( 'Главный баннер', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fb907f60652',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_hero_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => 150,
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fb90c760653',
				'label'             => esc_attr__( 'Описание', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_hero_description',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => 300,
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fb911760654',
				'label'             => esc_attr__( 'Кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_hero_cta',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),
			array(
				'key'               => 'field_68fb916760655',
				'label'             => esc_attr__( 'Преимущества', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_hero_advantages',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 4,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_68fb91a460656',
						'label'             => esc_attr__( 'Преимущество', 'xorit' ),
						'name'              => 'advantage',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 300,
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_68fb916760655',
					),
				),
			),
			array(
				'key'               => 'field_68fc79541c656',
				'label'             => esc_attr__( 'Задачи', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681c657',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91c658',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc813e1c659',
				'label'             => esc_attr__( 'Задачи', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_68fc817c1c65a',
						'label'             => esc_attr__( 'Иконка', 'xorit' ),
						'name'              => 'icon',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '10',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
						'parent_repeater'   => 'field_68fc813e1c659',
					),
					array(
						'key'               => 'field_68fc81f31c65b',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_68fc813e1c659',
					),
					array(
						'key'               => 'field_68fc82351c65c',
						'label'             => esc_attr__( 'Описание', 'xorit' ),
						'name'              => 'description',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 4,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_68fc813e1c659',
					),
				),
			),
			array(
				'key'               => 'field_68fc827d1c65d',
				'label'             => esc_attr__( 'Красная кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_cta_red',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),
			array(
				'key'               => 'field_68fc82a91c65e',
				'label'             => esc_attr__( 'Белая кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tasks_cta_white',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),

			array(
				'key'               => 'field_68fc79541chg4',
				'label'             => esc_attr__( 'Простой баннер', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xe45',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_simple_banner_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91cjj6',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_simple_banner_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => esc_attr__( 'Десктоп', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc79c91cbnr',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_simple_banner_title_mobile',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => esc_attr__( 'Мобайл', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc79c91cjk8',
				'label'             => esc_attr__( 'Описание', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_simple_banner_description',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 4,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fb911760jbf',
				'label'             => esc_attr__( 'Кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_simple_banner_cta',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),

			array(
				'key'               => 'field_68fc79541cnm5',
				'label'             => esc_attr__( 'Услуги', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xzz3',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_services_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91cjh4',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_services_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc813e1cmt5',
				'label'             => esc_attr__( 'Услуги', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_services_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_68fc817c1cxe7',
						'label'             => esc_attr__( 'Изображение', 'xorit' ),
						'name'              => 'image',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '20',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
						'parent_repeater'   => 'field_68fc813e1cmt5',
					),
					array(
						'key'               => 'field_69049b1bcff9b',
						'label'             => esc_attr__( 'Ссылка', 'xorit' ),
						'name'              => 'link',
						'aria-label'        => '',
						'type'              => 'url',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'parent_repeater'   => 'field_68fc813e1cmt5',
					),
					array(
						'key'               => 'field_68fc81f31cnm5',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_68fc813e1cmt5',
					),
				),
			),

			array(
				'key'               => 'field_6904a439b56f2',
				'label'             => esc_attr__( 'Табы', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xjn6',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tabs_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91cll4',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tabs_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => esc_attr__( 'Десктоп', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc79c91cmnj',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tabs_title_mobile',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => esc_attr__( 'Мобайл', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_6904a44fb56f3',
				'label'             => esc_attr__( 'Табы', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tabs_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => esc_attr__( 'Десктоп', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 5,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_6904a54bb56f4',
						'label'             => esc_attr__( 'Заголовок таба', 'xorit' ),
						'name'              => 'tab_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 20,
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'parent_repeater'   => 'field_6904a44fb56f3',
					),
					array(
						'key'               => 'field_6904a5a2b56f5',
						'label'             => esc_attr__( 'Описание', 'xorit' ),
						'name'              => 'description',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 0,
						'delay'             => 0,
						'parent_repeater'   => 'field_6904a44fb56f3',
					),
					array(
						'key'               => 'field_6904a5ddb56f6',
						'label'             => esc_attr__( 'Изображение', 'xorit' ),
						'name'              => 'image',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
						'parent_repeater'   => 'field_6904a44fb56f3',
					),
					array(
						'key'               => 'field_6904a5f5b56f7',
						'label'             => esc_attr__( 'Кнопка', 'xorit' ),
						'name'              => 'cta',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'allow_in_bindings' => 0,
						'parent_repeater'   => 'field_6904a44fb56f3',
					),
				),
			),
			array(
				'key'               => 'field_6904a44fb5nm7',
				'label'             => esc_attr__( 'Табы', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_tabs_items_mobile',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => esc_attr__( 'Мобайл', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 5,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_6904a54bb5x4h',
						'label'             => esc_attr__( 'Заголовок таба', 'xorit' ),
						'name'              => 'tab_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 20,
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'parent_repeater'   => 'field_6904a44fb5nm7',
					),
					array(
						'key'               => 'field_6904a5a2b5kl6',
						'label'             => esc_attr__( 'Описание', 'xorit' ),
						'name'              => 'description',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 0,
						'delay'             => 0,
						'parent_repeater'   => 'field_6904a44fb5nm7',
					),
					array(
						'key'               => 'field_6904a5ddb57u6',
						'label'             => esc_attr__( 'Изображение', 'xorit' ),
						'name'              => 'image',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
						'parent_repeater'   => 'field_6904a44fb5nm7',
					),
					array(
						'key'               => 'field_6904a5f5b5kj3',
						'label'             => esc_attr__( 'Кнопка', 'xorit' ),
						'name'              => 'cta',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'allow_in_bindings' => 0,
						'parent_repeater'   => 'field_6904a44fb5nm7',
					),
				),
			),

			array(
				'key'               => 'field_6904a439b5kj6',
				'label'             => esc_attr__( 'Преимущества', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xdd3',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_advantages_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_6904a5ddb5kl5',
				'label'             => esc_attr__( 'Изображение', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_advantages_image',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
				'allow_in_bindings' => 0,
				'preview_size'      => 'medium',
			),
			array(
				'key'               => 'field_68fc79c91cnm5',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_advantages_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_6904a44fb5je5',
				'label'             => esc_attr__( 'Преимущества', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_advantages_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 4,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_6904a54bb5cd8',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_6904a44fb5je5',
					),
					array(
						'key'               => 'field_6904a54bb5jk5',
						'label'             => esc_attr__( 'Описание', 'xorit' ),
						'name'              => 'description',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 4,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_6904a44fb5je5',
					),
				),
			),

			array(
				'key'               => 'field_6904a439b5bn5',
				'label'             => esc_attr__( 'Стек', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xmm6',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_stack_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91cnce',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_stack_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_6904a44fb5mk7',
				'label'             => esc_attr__( 'Стек', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_stack_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_6904a54bb5kw0',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_6904a44fb5mk7',
					),
				),
			),

			array(
				'key'               => 'field_6904a439b5nbn',
				'label'             => esc_attr__( 'Партнёры', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xxr5',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_partners_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91cnmr',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_partners_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_6904a44fb5mg7',
				'label'             => esc_attr__( 'Партнёры', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_partners_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_6904a5ddb5mm4',
						'label'             => esc_attr__( 'Изображение', 'xorit' ),
						'name'              => 'image',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
						'parent_repeater'   => 'field_6904a44fb5mg7',
					),
				),
			),

			array(
				'key'               => 'field_6904a439b5mg5',
				'label'             => esc_attr__( 'Клиенты', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xwq6',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_clients_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91cmm6',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_clients_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_6904a44fb5jh5',
				'label'             => esc_attr__( 'Элементы', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_clients_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_6904a54bb5xy5',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_6904a44fb5jh5',
					),
					array(
						'key'               => 'field_6904a5a2b5kjf',
						'label'             => esc_attr__( 'Описание', 'xorit' ),
						'name'              => 'description',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'tabs'              => 'all',
						'toolbar'           => 'list',
						'media_upload'      => 0,
						'delay'             => 0,
						'parent_repeater'   => 'field_6904a44fb5jh5',
					),
				),
			),
			array(
				'key'               => 'field_68fb911760jh6',
				'label'             => esc_attr__( 'Кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_clients_cta',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),

			array(
				'key'               => 'field_6904a439b5ss2',
				'label'             => esc_attr__( 'Заявка', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xzw3',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_request_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91bgh4',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_request_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc79c91bnbn',
				'label'             => esc_attr__( 'Описание', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_request_description',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 4,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fb76d2c1bnt',
				'label'             => esc_attr__( 'Телефон', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_request_phone',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => esc_attr__( 'Если не заполнено, используются настройки сайта', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_68fb76d2c1klk',
				'label'             => esc_attr__( 'Email', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_request_email',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => esc_attr__( 'Если не заполнено, используются настройки сайта', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_68fb911760mnj',
				'label'             => esc_attr__( 'Кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_request_cta',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),

			array(
				'key'               => 'field_6904a439b5cc4',
				'label'             => esc_attr__( 'Компании', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xre4',
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_companies_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91c00r',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_companies_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => esc_attr__( 'Десктоп', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc79c91ckl8',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_companies_title_mobile',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => esc_attr__( 'Мобайл', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_6904a44fb5klk',
				'label'             => esc_attr__( 'Логотипы', 'xorit' ),
				'name'              => Constants::ACF_FIELD_HOME . '_companies_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_6904a5ddb5ce8',
						'label'             => esc_attr__( 'Изображение', 'xorit' ),
						'name'              => 'image',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
						'parent_repeater'   => 'field_6904a44fb5klk',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page_type',
					'operator' => '==',
					'value'    => 'front_page',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
		'display_title'         => '',
	)
);
