<?php

use xoritTheme\Constants\Constants;
use function xoritTheme\ACF\FieldSets\get_simple_banner_fields;
use function xoritTheme\ACF\FieldSets\get_stack_fields;
use function xoritTheme\ACF\FieldSets\get_request_fields;
use function xoritTheme\ACF\FieldSets\get_services_fields;
use function xoritTheme\ACF\FieldSets\get_faq_fields;

$suffix = md5( Constants::ACF_FIELD_OPTIONS );

acf_add_local_field_group(
	array(
		'key'                   => 'group_68fb76ae37c70',
		'title'                 => esc_attr__( 'Настройки сайта', 'xorit' ),
		'fields'                => array(
			array(
				'key'               => 'field_68fb76aec1x33',
				'label'             => esc_attr__( 'Главные', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fb76d2c1xt5',
				'label'             => esc_attr__( 'Адрес', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_address',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_68fb76d2c1jhf',
				'label'             => esc_attr__( 'Телефон', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_phone',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_68fb76d2c15rf',
				'label'             => esc_attr__( 'Email', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_email',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'                  => 'field_690dab9b27dd6',
				'label'                => esc_attr__( 'Страница "Политика конфиденциальности"', 'xorit' ),
				'name'                 => Constants::ACF_FIELD_OPTIONS . '_privacy_policy',
				'aria-label'           => '',
				'type'                 => 'post_object',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'post_type'            => array(
					0 => 'page',
				),
				'post_status'          => array(
					0 => 'publish',
				),
				'taxonomy'             => '',
				'return_format'        => 'id',
				'multiple'             => 0,
				'allow_null'           => 0,
				'allow_in_bindings'    => 0,
				'bidirectional'        => 0,
				'ui'                   => 1,
				'bidirectional_target' => array(),
			),
			array(
				'key'                  => 'field_690dab9b27lk8',
				'label'                => esc_attr__( 'Страница "Согласие на обработку персональных данных"', 'xorit' ),
				'name'                 => Constants::ACF_FIELD_OPTIONS . '_personal_data',
				'aria-label'           => '',
				'type'                 => 'post_object',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'post_type'            => array(
					0 => 'page',
				),
				'post_status'          => array(
					0 => 'publish',
				),
				'taxonomy'             => '',
				'return_format'        => 'id',
				'multiple'             => 0,
				'allow_null'           => 0,
				'allow_in_bindings'    => 0,
				'bidirectional'        => 0,
				'ui'                   => 1,
				'bidirectional_target' => array(),
			),
			array(
				'key'               => 'field_690ef62b70mn6',
				'label'             => esc_attr__( 'Куки', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_cookies',
				'aria-label'        => '',
				'type'              => 'wysiwyg',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'allow_in_bindings' => 0,
				'tabs'              => 'all',
				'toolbar'           => 'mini',
				'media_upload'      => 0,
				'delay'             => 0,
			),
			array(
				'key'               => 'field_68fb76aec1f82',
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fb76d2c1f83',
				'label'             => esc_attr__( 'Текст лого', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_logo_text',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => esc_attr__( 'Аутсорсинг IT специалистов', 'xorit' ),
				'maxlength'         => 150,
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),

			// Simple banner
			...get_simple_banner_fields(
				Constants::ACF_FIELD_OPTIONS,
				array(
					'show_hide_toggle'          => false,
					'title_instructions'        => esc_attr__( 'Десктоп', 'xorit' ),
					'title_mobile_instructions' => esc_attr__( 'Мобайл', 'xorit' ),
					'description_instructions'  => '',
					'cta_instructions'          => '',
					'image_instructions'        => '',
				)
			),

			// Stack
			...get_stack_fields(
				Constants::ACF_FIELD_OPTIONS,
				array(
					'show_hide_toggle'          => false,
					'title_instructions'        => esc_attr__( 'Десктоп', 'xorit' ),
					'title_mobile_instructions' => esc_attr__( 'Мобайл', 'xorit' ),
					'items_instructions'        => '',
				)
			),

			// Request
			...get_request_fields(
				Constants::ACF_FIELD_OPTIONS,
				array(
					'show_hide_toggle'         => false,
					'hide_contacts'            => true,
					'title_instructions'       => '',
					'description_instructions' => '',
					'cta_instructions'         => '',
					'threats_instructions'     => '',
				)
			),

			// Services
			...get_services_fields(
				Constants::ACF_FIELD_OPTIONS,
				array(
					'show_hide_toggle'   => false,
					'title_instructions' => '',
					'items_instructions' => '',
				)
			),

			// FAQ
			...get_faq_fields(
				Constants::ACF_FIELD_OPTIONS,
				array(
					'show_hide_toggle'   => false,
					'title_instructions' => '',
					'items_instructions' => '',
				)
			),

			// Footer
			array(
				'key'               => 'field_6904a439b5hj6',
				'label'             => esc_attr__( 'Подвал', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_6904a5ddb5xe4',
				'label'             => esc_attr__( 'Логотип', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_footer_logo',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
				'allow_in_bindings' => 0,
				'preview_size'      => 'medium',
			),
			array(
				'key'               => 'field_68fb76d2c1kkl',
				'label'             => esc_attr__( 'Адрес', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_footer_address',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => esc_attr__( 'Если не заполнено, используются настройки сайта', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_68fb76d2c1hj4',
				'label'             => esc_attr__( 'Телефон', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_footer_phone',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => esc_attr__( 'Если не заполнено, используются настройки сайта', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_68fb76d2c1llq',
				'label'             => esc_attr__( 'Email', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_footer_email',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => esc_attr__( 'Если не заполнено, используются настройки сайта', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_68fb76d2c1lkl',
				'label'             => esc_attr__( 'Заголовок формы', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_footer_form_title',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'                  => 'field_690de1cf41bed',
				'label'                => esc_attr__( 'Форма', 'xorit' ),
				'name'                 => Constants::ACF_FIELD_OPTIONS . '_footer_form',
				'aria-label'           => '',
				'type'                 => 'post_object',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'post_type'            => array(
					0 => 'wpcf7_contact_form',
				),
				'post_status'          => array(
					0 => 'publish',
				),
				'taxonomy'             => '',
				'return_format'        => 'id',
				'multiple'             => 0,
				'allow_null'           => 0,
				'allow_in_bindings'    => 0,
				'bidirectional'        => 0,
				'ui'                   => 1,
				'bidirectional_target' => array(),
			),
			array(
				'key'               => 'field_68fb911760jnr',
				'label'             => esc_attr__( 'Кнопка', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_footer_cta',
				'aria-label'        => '',
				'type'              => 'link',
				'instructions'      => esc_attr__( 'Мобайл', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'allow_in_bindings' => 0,
			),

			array(
				'key'               => 'field_690ef50270d35',
				'label'             => esc_attr__( 'Попапы', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_690ef51670d36',
				'label'             => esc_attr__( 'Закажите звонок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_popup_callback',
				'aria-label'        => '',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'sub_fields'        => array(
					array(
						'key'                  => 'field_690ef60670d37',
						'label'                => esc_attr__( 'Форма', 'xorit' ),
						'name'                 => 'form',
						'aria-label'           => '',
						'type'                 => 'post_object',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'post_type'            => array(
							0 => 'wpcf7_contact_form',
						),
						'post_status'          => array(
							0 => 'publish',
						),
						'taxonomy'             => '',
						'return_format'        => 'id',
						'multiple'             => 0,
						'allow_null'           => 0,
						'allow_in_bindings'    => 0,
						'bidirectional'        => 0,
						'ui'                   => 1,
						'bidirectional_target' => array(),
					),
					array(
						'key'               => 'field_690ef62b70d38',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => esc_attr__( 'Десктоп', 'xorit' ),
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 250,
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
					),
					array(
						'key'               => 'field_690ef62b70hj6',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title_mobile',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => esc_attr__( 'Мобайл', 'xorit' ),
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 250,
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
					),
				),
			),
			array(
				'key'               => 'field_690ef51670jk5',
				'label'             => esc_attr__( 'Заявка отправлена', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_popup_success',
				'aria-label'        => '',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'sub_fields'        => array(
					array(
						'key'               => 'field_690ef62b70df3',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 250,
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
					),
					array(
						'key'               => 'field_690ef62b70jkj',
						'label'             => esc_attr__( 'Описание', 'xorit' ),
						'name'              => 'description',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 4,
						'placeholder'       => '',
						'new_lines'         => 'br',
					),
					array(
						'key'               => 'field_690ef62b70lkl',
						'label'             => esc_attr__( 'Текст кнопки', 'xorit' ),
						'name'              => 'button_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 20,
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
				),
			),
			array(
				'key'               => 'field_690ef51670ll8',
				'label'             => esc_attr__( 'Ошибка отправки', 'xorit' ),
				'name'              => Constants::ACF_FIELD_OPTIONS . '_popup_error',
				'aria-label'        => '',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'sub_fields'        => array(
					array(
						'key'               => 'field_690ef62b70mg6',
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 250,
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
					),
					array(
						'key'               => 'field_690ef62b70mq2',
						'label'             => esc_attr__( 'Описание', 'xorit' ),
						'name'              => 'description',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 4,
						'placeholder'       => '',
						'new_lines'         => 'br',
					),
					array(
						'key'               => 'field_690ef62b70mm7',
						'label'             => esc_attr__( 'Текст кнопки', 'xorit' ),
						'name'              => 'button_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 20,
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'xorit-options',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
		'display_title'         => '',
	)
);
