<?php

use xoritTheme\Constants\Constants;
use function xoritTheme\ACF\FieldSets\get_infofraph_fields;
use function xoritTheme\ACF\FieldSets\get_advantages_fields;
use function xoritTheme\ACF\FieldSets\get_services_fields;
use function xoritTheme\ACF\FieldSets\get_request_fields;

$key    = Constants::ACF_FIELD_SERVICES . '_child';
$suffix = md5( $key );

acf_add_local_field_group(
	array(
		'key'                   => 'group_services_child_' . $suffix,
		'title'                 => esc_attr__( 'Дочерняя услуга', 'xorit' ),
		'fields'                => array(
			array(
				'key'               => 'field_6929b81daekjk' . $suffix,
				'label'             => esc_attr__( 'Превью', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79c91ckj7' . $suffix,
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => $key . '_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc79c91ccdk' . $suffix,
				'label'             => esc_attr__( 'Описание', 'xorit' ),
				'name'              => $key . '_description',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 4,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_692c86a4c9jkj' . $suffix,
				'label'             => esc_attr__( 'Список', 'xorit' ),
				'name'              => $key . '_list',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_692c8702c9mh5' . $suffix,
						'label'             => esc_attr__( 'Пункт', 'xorit' ),
						'name'              => 'item',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 2,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_692c86a4c9jkj' . $suffix,
					),
				),
			),
			array(
				'key'               => 'field_68fc79c91cjjh' . $suffix,
				'label'             => esc_attr__( 'Цитата', 'xorit' ),
				'name'              => $key . '_quote',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc79681xddh' . $suffix,
				'label'             => esc_attr__( 'Скрыть кнопку', 'xorit' ),
				'name'              => $key . '_cta_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),

			// Hero (Infographics)
			...get_infofraph_fields(
				$key,
				array(
					'tab_label'          => esc_attr__( 'Заголовок', 'xorit' ),
					'first_group_label'  => esc_attr__( 'Проблема', 'xorit' ),
					'second_group_label' => esc_attr__( 'Решение', 'xorit' ),
				)
			),

			// Simple Three Cards
			array(
				'key'               => 'field_6929b81daejjn' . $suffix,
				'label'             => esc_attr__( 'Карточки', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xnd7' . $suffix,
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => $key . '_simple_cards_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_68fc79c91cxxt' . $suffix,
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => $key . '_simple_cards_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_692c86a4c9kk6' . $suffix,
				'label'             => esc_attr__( 'Карточки', 'xorit' ),
				'name'              => $key . '_simple_cards_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_692c8702c9hn5' . $suffix,
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 4,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_692c86a4c9kk6' . $suffix,
					),
				),
			),

			// Advantages
			...get_advantages_fields( $key ),

			// Services
			...get_services_fields( $key ),

			// Request
			...get_request_fields( $key ),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => Constants::PT_SLUG_SERVICES,
				),
				array(
					'param'    => 'post_parent',
					'operator' => '!=',
					'value'    => '0',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
		'display_title'         => '',
	)
);
