<?php

use xoritTheme\Constants\Constants;
use function xoritTheme\ACF\FieldSets\get_simple_banner_fields;
use function xoritTheme\ACF\FieldSets\get_stack_fields;
use function xoritTheme\ACF\FieldSets\get_request_fields;
use function xoritTheme\ACF\FieldSets\get_services_fields;
use function xoritTheme\ACF\FieldSets\get_faq_fields;
use function xoritTheme\ACF\FieldSets\get_advantages_fields;
use function xoritTheme\ACF\FieldSets\get_hero_fields;

$suffix = md5( Constants::ACF_FIELD_SERVICES );

acf_add_local_field_group(
	array(
		'key'                   => 'group_6929b81d53426' . $suffix,
		'title'                 => esc_attr__( 'Услуги', 'xorit' ),
		'fields'                => array(
			array(
				'key'               => 'field_6929b81dae954' . $suffix,
				'label'             => esc_attr__( 'Превью', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79c91cll9' . $suffix,
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_preview_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => esc_attr__( 'Используется заголовок поста, если пусто', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_68fc817c1cne3' . $suffix,
				'label'             => esc_attr__( 'Изображение', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_preview_image',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => esc_attr__( 'Десктоп', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
				'allow_in_bindings' => 0,
				'preview_size'      => 'medium',
			),
			array(
				'key'               => 'field_68fc817c1cnmv' . $suffix,
				'label'             => esc_attr__( 'Изображение', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_preview_image_mobile',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => esc_attr__( 'Мобайл', 'xorit' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
				'allow_in_bindings' => 0,
				'preview_size'      => 'medium',
			),

			// Hero
			...get_hero_fields( Constants::ACF_FIELD_SERVICES ),

			// Cards
			array(
				'key'               => 'field_692c867bc9f13' . $suffix,
				'label'             => esc_attr__( 'Карточки', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_68fc79681xkjt' . $suffix,
				'label'             => esc_attr__( 'Скрыть блок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_cards_hide',
				'aria-label'        => '',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'allow_in_bindings' => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_692c86a4c9f14' . $suffix,
				'label'             => esc_attr__( 'Карточки', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_cards_items',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'table',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'               => 'field_692c86dfc9f15' . $suffix,
						'label'             => esc_attr__( 'Изображение', 'xorit' ),
						'name'              => 'image',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '20',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
						'parent_repeater'   => 'field_692c86a4c9f14' . $suffix,
					),
					array(
						'key'               => 'field_692c8702c9f16' . $suffix,
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 250,
						'allow_in_bindings' => 0,
						'rows'              => 4,
						'placeholder'       => '',
						'new_lines'         => 'br',
						'parent_repeater'   => 'field_692c86a4c9f14' . $suffix,
					),
				),
			),

			// Infographic
			array(
				'key'               => 'field_692dd146b4efe' . $suffix,
				'label'             => esc_attr__( 'Инфографика', 'xorit' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
				'selected'          => 0,
			),
			array(
				'key'               => 'field_692dd7fed4be6' . $suffix,
				'label'             => esc_attr__( 'Изображение', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_infograph_image',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
				'allow_in_bindings' => 0,
				'preview_size'      => 'medium',
			),
			array(
				'key'               => 'field_692dd15fb4eff' . $suffix,
				'label'             => esc_attr__( 'Заголовок', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_infograph_title',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => 150,
				'allow_in_bindings' => 0,
				'rows'              => 2,
				'placeholder'       => '',
				'new_lines'         => 'br',
			),
			array(
				'key'               => 'field_692dd207b4f00' . $suffix,
				'label'             => esc_attr__( 'Что делаете вы', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_infograph_you',
				'aria-label'        => '',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'sub_fields'        => array(
					array(
						'key'               => 'field_692dd23bb4f01' . $suffix,
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 150,
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_692dd264b4f02' . $suffix,
						'label'             => esc_attr__( 'Описание', 'xorit' ),
						'name'              => 'description',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => 4,
						'placeholder'       => '',
						'new_lines'         => 'br',
					),
				),
			),
			array(
				'key'               => 'field_692dd29fdd23c' . $suffix,
				'label'             => esc_attr__( 'Что делаем мы', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_infograph_we',
				'aria-label'        => '',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'sub_fields'        => array(
					array(
						'key'               => 'field_692dd2d4dd23d' . $suffix,
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 150,
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_692dd317dd23e' . $suffix,
						'label'             => esc_attr__( 'Пункты', 'xorit' ),
						'name'              => 'points',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_692dd348dd23f' . $suffix,
								'label'             => esc_attr__( 'Пункт', 'xorit' ),
								'name'              => 'point',
								'aria-label'        => '',
								'type'              => 'textarea',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'allow_in_bindings' => 0,
								'rows'              => 2,
								'placeholder'       => '',
								'new_lines'         => 'br',
								'parent_repeater'   => 'field_692dd317dd23e' . $suffix,
							),
						),
					),
				),
			),
			array(
				'key'               => 'field_692dd38d9c00f' . $suffix,
				'label'             => esc_attr__( 'Карточки', 'xorit' ),
				'name'              => Constants::ACF_FIELD_SERVICES . '_infograph_cards',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'pagination'        => 0,
				'min'               => 0,
				'max'               => 0,
				'collapsed'         => '',
				'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
				'rows_per_page'     => 20,
				'sub_fields'        => array(
					array(
						'key'                   => 'field_692dd62b9c011' . $suffix,
						'label'                 => esc_attr__( 'Цвет бэкграунда', 'xorit' ),
						'name'                  => 'background',
						'aria-label'            => '',
						'type'                  => 'color_picker',
						'instructions'          => '',
						'required'              => 0,
						'conditional_logic'     => 0,
						'wrapper'               => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'         => '',
						'enable_opacity'        => 0,
						'return_format'         => 'string',
						'allow_in_bindings'     => 0,
						'show_custom_palette'   => 0,
						'show_color_wheel'      => 1,
						'custom_palette_source' => '',
						'palette_colors'        => '',
						'parent_repeater'       => 'field_692dd38d9c00f' . $suffix,
					),
					array(
						'key'                   => 'field_692dd6b09c012' . $suffix,
						'label'                 => esc_attr__( 'Цвет текста', 'xorit' ),
						'name'                  => 'color',
						'aria-label'            => '',
						'type'                  => 'color_picker',
						'instructions'          => '',
						'required'              => 0,
						'conditional_logic'     => 0,
						'wrapper'               => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'         => '',
						'enable_opacity'        => 0,
						'return_format'         => 'string',
						'allow_in_bindings'     => 0,
						'show_custom_palette'   => 0,
						'show_color_wheel'      => 1,
						'custom_palette_source' => '',
						'palette_colors'        => '',
						'parent_repeater'       => 'field_692dd38d9c00f' . $suffix,
					),
					array(
						'key'               => 'field_692dd5729c010' . $suffix,
						'label'             => esc_attr__( 'Заголовок', 'xorit' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 150,
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'parent_repeater'   => 'field_692dd38d9c00f' . $suffix,
					),
					array(
						'key'               => 'field_692dd70ed7f7b' . $suffix,
						'label'             => esc_attr__( 'Пункты', 'xorit' ),
						'name'              => 'points',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => esc_attr__( 'Добавить', 'xorit' ),
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_692dd73ad7f7c' . $suffix,
								'label'             => '',
								'name'              => 'yes_no',
								'aria-label'        => '',
								'type'              => 'true_false',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '20',
									'class' => '',
									'id'    => '',
								),
								'message'           => '',
								'default_value'     => 0,
								'allow_in_bindings' => 0,
								'ui_on_text'        => esc_attr__( 'Да', 'xorit' ),
								'ui_off_text'       => esc_attr__( 'Нет', 'xorit' ),
								'ui'                => 1,
								'parent_repeater'   => 'field_692dd70ed7f7b' . $suffix,
							),
							array(
								'key'               => 'field_692dd7c2d7f7d' . $suffix,
								'label'             => esc_attr__( 'Пункт', 'xorit' ),
								'name'              => 'point',
								'aria-label'        => '',
								'type'              => 'textarea',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'allow_in_bindings' => 0,
								'rows'              => 4,
								'placeholder'       => '',
								'new_lines'         => 'br',
								'parent_repeater'   => 'field_692dd70ed7f7b' . $suffix,
							),
						),
						'parent_repeater'   => 'field_692dd38d9c00f' . $suffix,
					),
				),
			),

			// Advantages
			...get_advantages_fields(
				Constants::ACF_FIELD_SERVICES,
				array(
					'hide_images' => true,
				)
			),

			// Single banner
			...get_simple_banner_fields( Constants::ACF_FIELD_SERVICES ),

			// Stack
			...get_stack_fields( Constants::ACF_FIELD_SERVICES ),

			// Request
			...get_request_fields( Constants::ACF_FIELD_SERVICES ),

			// Services
			...get_services_fields( Constants::ACF_FIELD_SERVICES ),

			// FAQ
			...get_faq_fields( Constants::ACF_FIELD_SERVICES ),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => Constants::PT_SLUG_SERVICES,
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
		'display_title'         => '',
	)
);
